# Thank you to Qwik.js documentation for providing guidance on GitHub-pages deployment: https://qwik.dev/docs/deployments/github-pages/

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with: 
          node-version: '24.8.0'
          cache: 'bun' #Setup-node action cache is faster for a project structure/directories that share multiple dependencies than Cache action.

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build the project
        run: bun run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
      
      
